name: Build Docker Image and Run Docker on Server 
on:
  push:
    branches:
      - master

jobs:
    docker-image:
      runs-on: ubuntu-latest
      name: Docker Image Build and Run
      steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image and Push
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{secrets.DOCKER_USERNAME}}/kuics-frontend
          tags: latest
      - name: Clean Up
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker rm --force kuics-frontend && docker rmi kuicsofficial/kuics-frontend
          host: ${{secrets.SERVER}}
          username: ${{secrets.USERNAME}}
          privateKey: ${{secrets.PRIVATE_KEY}}
      - name: Run Docker
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}} && docker pull ${{secrets.DOCKER_USERNAME}}/kuics-frontend && docker run -d -v /home/ubuntu/log/frontend:/kuics-frontend/log -p ${{secrets.HOST_PORT}}:${{secrets.PORT}} --name kuics-frontend ${{secrets.DOCKER_USERNAME}}/kuics-frontend
          host: ${{secrets.SERVER}}
          username: ${{secrets.USERNAME}}
          privateKey: ${{secrets.PRIVATE_KEY}}
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Check Build Status
        run: wget test.kuics.kro.kr
